/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateListingArgs {
  'title' : string,
  'size' : [] | [string],
  'description' : string,
  'category' : string,
  'brand' : [] | [string],
  'priceInCents' : bigint,
  'condition' : ListingCondition,
  'images' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : ListingId,
  'status' : ListingStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'size' : [] | [string],
  'description' : string,
  'sellerName' : [] | [string],
  'updatedAt' : Timestamp,
  'category' : string,
  'brand' : [] | [string],
  'sellerId' : UserId,
  'priceInCents' : bigint,
  'condition' : ListingCondition,
  'images' : Array<ExternalBlob>,
}
export type ListingCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null };
export type ListingId = bigint;
export interface ListingPage {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'listings' : Array<Listing>,
}
export type ListingStatus = { 'deleted' : null } |
  { 'active' : null } |
  { 'sold' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'listingId' : ListingId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'sellerId' : UserId,
  'stripeSessionId' : string,
  'priceInCents' : bigint,
}
export type OrderId = bigint;
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateListingArgs {
  'id' : ListingId,
  'title' : string,
  'size' : [] | [string],
  'description' : string,
  'category' : string,
  'brand' : [] | [string],
  'priceInCents' : bigint,
  'condition' : ListingCondition,
  'images' : Array<ExternalBlob>,
}
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'avatarUrl' : [] | [ExternalBlob],
  'listingCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createListing' : ActorMethod<[CreateListingArgs], Listing>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'getActiveListings' : ActorMethod<[bigint, bigint], ListingPage>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[ListingId], [] | [Listing]>,
  'getMyListings' : ActorMethod<[], Array<Listing>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markListingAsSold' : ActorMethod<[ListingId], undefined>,
  'placeOrder' : ActorMethod<[ListingId, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<
    [string, [] | [string], bigint, bigint],
    ListingPage
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateListing' : ActorMethod<[UpdateListingArgs], undefined>,
  'updateOrderStatusFromSession' : ActorMethod<[string], [] | [Order]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];