/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ListingCondition = IDL.Variant({
  'new' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'likeNew' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateListingArgs = IDL.Record({
  'title' : IDL.Text,
  'size' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Opt(IDL.Text),
  'priceInCents' : IDL.Nat,
  'condition' : ListingCondition,
  'images' : IDL.Vec(ExternalBlob),
});
export const ListingId = IDL.Nat;
export const ListingStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'active' : IDL.Null,
  'sold' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const UserId = IDL.Principal;
export const Listing = IDL.Record({
  'id' : ListingId,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'size' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'sellerName' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'category' : IDL.Text,
  'brand' : IDL.Opt(IDL.Text),
  'sellerId' : UserId,
  'priceInCents' : IDL.Nat,
  'condition' : ListingCondition,
  'images' : IDL.Vec(ExternalBlob),
});
export const ListingPage = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'listings' : IDL.Vec(Listing),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'avatarUrl' : IDL.Opt(ExternalBlob),
  'listingCount' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'listingId' : ListingId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'sellerId' : UserId,
  'stripeSessionId' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateListingArgs = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'size' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Opt(IDL.Text),
  'priceInCents' : IDL.Nat,
  'condition' : ListingCondition,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createListing' : IDL.Func([CreateListingArgs], [Listing], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'getActiveListings' : IDL.Func([IDL.Nat, IDL.Nat], [ListingPage], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markListingAsSold' : IDL.Func([ListingId], [], []),
  'placeOrder' : IDL.Func([ListingId, IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [ListingPage],
      ['query'],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateListing' : IDL.Func([UpdateListingArgs], [], []),
  'updateOrderStatusFromSession' : IDL.Func([IDL.Text], [IDL.Opt(Order)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ListingCondition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'likeNew' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateListingArgs = IDL.Record({
    'title' : IDL.Text,
    'size' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Opt(IDL.Text),
    'priceInCents' : IDL.Nat,
    'condition' : ListingCondition,
    'images' : IDL.Vec(ExternalBlob),
  });
  const ListingId = IDL.Nat;
  const ListingStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'active' : IDL.Null,
    'sold' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const UserId = IDL.Principal;
  const Listing = IDL.Record({
    'id' : ListingId,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'size' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'sellerName' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'category' : IDL.Text,
    'brand' : IDL.Opt(IDL.Text),
    'sellerId' : UserId,
    'priceInCents' : IDL.Nat,
    'condition' : ListingCondition,
    'images' : IDL.Vec(ExternalBlob),
  });
  const ListingPage = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'listings' : IDL.Vec(Listing),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'avatarUrl' : IDL.Opt(ExternalBlob),
    'listingCount' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'listingId' : ListingId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'buyerId' : UserId,
    'sellerId' : UserId,
    'stripeSessionId' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateListingArgs = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'size' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Opt(IDL.Text),
    'priceInCents' : IDL.Nat,
    'condition' : ListingCondition,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createListing' : IDL.Func([CreateListingArgs], [Listing], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'getActiveListings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [ListingPage],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markListingAsSold' : IDL.Func([ListingId], [], []),
    'placeOrder' : IDL.Func([ListingId, IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [ListingPage],
        ['query'],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateListing' : IDL.Func([UpdateListingArgs], [], []),
    'updateOrderStatusFromSession' : IDL.Func([IDL.Text], [IDL.Opt(Order)], []),
  });
};

export const init = ({ IDL }) => { return []; };